### ISSUE TITLE
ECS Task: Specify pre-existing log group

### ISSUE THREAD

**Issue by BadAsstronaut** [PrefectHQ/prefect-aws#114]
When enabling CloudWatch logs for flows executing in an ECSTask infra block, it generates a new CW log group of "prefect." I would like to provide a reference to an existing log group and specify the log prefix for new streams.

**Comment by madkinsz** [comment]
Let me know if that pull request satisfies your needs.

**Comment by BadAsstronaut** [comment]
> Let me know if that pull request satisfies your needs.

Awesome! Thanks for the quick turn around.
