### ISSUE TITLE
Add ECS example on README for visibility

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/prefect-aws#123]
Similar to
https://github.com/PrefectHQ/prefect-gcp#deploy-command-on-cloud-run

**Comment by manugarri** [comment]
+1 to this, i am bashing my head porting an airflow ecs operator to prefect-aws and cant find a single example on how to use it properly

**Comment by madkinsz** [comment]
@manugarri there are many examples at https://prefecthq.github.io/prefect-aws/ecs/ — there's also a description in our main documentation at https://docs.prefect.io/concepts/infrastructure/#ecstask with links to some more resources. See https://docs.prefect.io/concepts/infrastructure/#infrastructure-overview for general instructions on how to use infrastructure.
