### ISSUE TITLE
If container name in task-def is not prefect throws Client Exception

### ISSUE THREAD

**Issue by DVD-99** [PrefectHQ/prefect-aws#159]
If we want to use an image from a task-def ARN, we must set `image=None` in the ECSTask class, but I got `botocore.errorfactory. ClientException: When calling the RegisterTaskDefinition operation, an error (ClientException) occurred: The container.image should not be null or empty`.
This problem was resolved by changing the container name in task-def to **prefect**. There was no mention of this in the documentation. I'm not sure if this will be a problem for some users.

**Comment by madkinsz** [comment]
We require one of the container names to be `prefect` so we know where to inject the command to start the flow run.

We should definitely clarify this in documentation.

**Comment by DVD-99** [comment]
Yeah updating the documentation would be a good idea. Thanks
