### ISSUE TITLE
Prefect deployment expecting string on basepath not `pathlib.Path`.

### ISSUE THREAD

**Issue by lsetiawan** [PrefectHQ/prefect-aws#161]
## Overview

This is similar to issue found in the `prefect` repo (https://github.com/PrefectHQ/prefect/issues/7583), where `AttributeError` is encountered when trying to build deployment with `s3-bucket` storage block type. As I mentioned in the other issue `S3Bucket` attribute of `basepath` is `pathlib.Path` type not `str`, which caused the error I think:

https://github.com/PrefectHQ/prefect-aws/blob/519105bb757802fb31953645efa2824aca81dfc7/prefect_aws/s3.py#L272-L276

**Comment by ahuang11** [comment]
Thanks for reporting this. Would you be interested in contributing a PR to fix this?
