### ISSUE TITLE
Add AWS region to S3 block configuration

### ISSUE THREAD

**Issue by vembloud** [PrefectHQ/prefect-aws#173]
### Problem
Deployment push (during build) and pull (when agent runs flow) using S3 block is dependent on region set in environment (AWS_REGION or ~/.aws/config). If S3 bucket is in different region, push/pull fails with "Access denied".

### Workaround

Set AWS_REGION when deploying or running agent (problematic when multiple regions are used)

### Possible solutions

- Add region to S3 block configuration
- Determine bucket's region automatically on access

**Comment by desertaxle** [comment]
Thanks for opening an issue @vembloud! If you're using the `S3Bucket` block in this library you can set the AWS region on the `AwsCredentials` block that is nested under the `S3Bucket` block. Does that provide the configurability that you need, or is additional configurability required?

**Comment by vembloud** [comment]
It looks like the issue belongs somewhere else - it's related to `prefect.filesystems.S3`
