### ISSUE TITLE
Make S3Bucket._resolve_path Windows-friendly

### ISSUE THREAD

**Issue by dominictarro** [PrefectHQ/prefect-aws#188]
https://github.com/PrefectHQ/prefect-aws/blob/7748ffe63826996dc0e2d5cf9e3d72daba5b8a39/prefect_aws/s3.py#L394

Read/write from Windows OS produced object keys with backslashes and no folder hierarchy. This was due to `pathlib` inferring backslashes on Windows. Backslashes are frowned upon in [AWS Object key naming guidelines](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html).

Explicitly madke `Path` return a POSIX path string.

```py
        # If basepath provided, it means we won't write to the root dir of
        # the bucket. So we need to add it on the front of the path.
        # 
        # AWS object key naming guidelines require '/'. Get POSIX path to prevent
        # Path from inferring '\' on Windows OS
        path = (Path(self.basepath) / path).as_posix() if self.basepath else path
```

**Comment by ahuang11** [comment]
Thanks for reporting! Would you be interested in contributing a PR to fix this?

If so, here are the steps to [help!](https://github.com/PrefectHQ/prefect-aws#contribute)
