### ISSUE TITLE
Infer container definition name instead of requiring 'prefect'

### ISSUE THREAD

**Issue by rjhawar** [PrefectHQ/prefect-aws#196]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When you create a task definition using ECS block and add task definition by default prefect add second container definition called "prefect". The system should not be adding the default prefect container definition if you add your container definition with the appropriate  values. 

The other issue that occurs is when you add value to the name field the task deinition will still be set as"prefect" instead of the name you entered.
```
{
    "containerDefinitions": [
        {
            "name": "test_util_ecs_job",
            "image": "xxx.dkr.ecr.eu-west-1.amazonaws.com/test_util",
            "cpu": 0,
            "portMappings": [],
            "essential": true,
            "environment": [
                {
                    "name": "test",
                    "value": "TEST"
                }
            ],
            "mountPoints": [],
            "volumesFrom": []
        },
        {
            "name": "prefect",
            "image": "xxx.ecr.eu-west-1.amazonaws.com/test_util",
            "cpu": 0,
            "portMappings": [],
            "essential": true,
            "environment": [],
            
```

### Reproduction

```python3
1. Create an ECS block, 
2. Add task definition (I didn't use the task arn field for this one)
3. Create a flow run
4. Examine the task definition and see that the default prefect definition is still present
```

### Versions

```Text
Version:
Prefect 2.7.8
Python: 3.11.1
Prefect-aws: 0.2.3
```

**Comment by madkinsz** [comment]
Can you please share an executable example that demonstrates your issue? `ECSTask` can be used without flow runs, e.g.

```python
ECSTask(command=["prefect", "version"]).run()
```

Then share the details of the task definitions present on AWS?

**Comment by rjhawar** [comment]
@madkinsz 

I did a little bit more digging and found the issue. If I add a task definition and change the name from "prefect" to something else the resulting task json will contain two task definitions, same as what I displayed above. If you set the "name:" field to "prefect" everything works fine. You can even specify two different images for both task definitions (see second example).

example 1:
```
ECSTask(
command=["prefect", "version"],
image = "prefecthq/prefect:2.7.9-python3.11",
task_definition = {"containerDefinitions": [
        {
            "name": "test_util_ecs_job",
            "environment": [{"name": "ENV_TYPE", "value": "PROD"}]
        }
    ]}
).run()
```

example 2:
```
ECSTask(
command=["prefect", "version"],
image = "prefecthq/prefect:2.7.9-python3.11",
task_definition = {"containerDefinitions": [
        {
            "name": "test_util_ecs_job",
            "image": "prefecthq/prefect:2.7.9-python3.9"
            "environment": [{"name": "test", "value": "TEST"}]
        }
    ]}
).run()
```

"containerDefinitions": [
        {
            "name": "test_util_ecs_job,
            "image": "prefecthq/prefect:2.7.9-python3.9",
            "cpu": 0,
            "portMappings": [],
            "essential": true,
            "environment": [
                {
                    "name": "test",
                    "value": "TEST"
                }
            ],
            "mountPoints": [],
            "volumesFrom": []
        },
        {
            "name": "prefect",
            "image": "prefecthq/prefect:2.7.9-python3.11",
            "cpu": 0,
            "portMappings": [],
            "essential": true,
            "environment": [],
            "mountPoints": [],
            "volumesFrom": []
        }
    ],

**Comment by madkinsz** [comment]
I see. Thanks for the additional examples! We have a ticket at #174 to add documentation about this, but we need to know which container definition to set the `command` for and it is hard-coded to the one named "prefect". As you've noticed, this means you can run separate containers alongside the one that we are managing! We just need to know the name of the one we are supposed to manage. Does that clear things up?

**Comment by rjhawar** [comment]
@madkinsz yea it does clear up things for me. 
I am not fan of the current implementation would it be feasible to change the behaviour so that it selects user's inputted name and only default to prefect if no name is added.

**Comment by madkinsz** [comment]
@rjhawar that could be a breaking change. Why do you care what the container is named?

**Comment by rjhawar** [comment]
@madkinsz My concern was more with the behaviour and how strange and non-intuitive it feels:

For instance this is another case where you can potentially run into a problem:
If you were to create your own task definition in AWS and then use the task ARN for your block. If the container definition name wasn't set to "prefect" then you would encounter the same issue.

**Comment by madkinsz** [comment]
Hm. Let me poke around and see if there's a reasonable way we can get the behavior you're looking for.
