### ISSUE TITLE
ECS block should have an optional field for ephemeralStorage

### ISSUE THREAD

**Issue by rjhawar** [PrefectHQ/prefect-aws#197]
# Expectation / Proposal
ECS block is missing a field for ephemeralStorage. It would be nice if we could get that added as an optional field. This is very useful if you want to adjust the default size from 20GB up to 200GB for a fargate instance 

Currently you have to add the value as an task definition, this is not documented in the prefect-aws docs or in Anna's examples:
```
task_definition = {ephemeralStorage: {'sizeInGiB': disk}}
```

# Traceback / Example

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

**Comment by madkinsz** [comment]
Hi! We try to limit the amount of fields we add and you can do this via the `task_definition` field or the `task_customizations` field — would it suffice for us to add an example for this use?

**Comment by rjhawar** [comment]
Yea examples would be great to have and that would work in my case since i am using a CI to register my flows. I would be curious to see how it is done via task_customization. 

side note:
I think ECS is pretty popular it would always be nice to have this connivence option in the GUI so you didn't have to go and add json to enable it. If it could implement in a way that only enables the field once launch type is set to fargate or fargate spot that would be the most ideal.
