### ISSUE TITLE
Credentials loading only works with Deprecated method

### ISSUE THREAD

**Issue by jralduaveuthey** [PrefectHQ/prefect-aws#202]
I am using prefect-aws 0.2.4.

When creating a S3Bucket block over the Prefect UI it is not possible to link the AWS Credentials block using the recommented method.  It only works with the [DEPRECATED] method.

![image](https://user-images.githubusercontent.com/3756919/214323076-33f2f832-bb60-4cf2-9fd6-4702e6e01440.png)

**Comment by desertaxle** [comment]
Thanks for raising this issue @jralduaveuthey! We’re aware of this bug and we’re tracking the underlying issue in https://github.com/PrefectHQ/orion-design/issues/979. If you set your credentials via the `.save()` method in the Python client, then it should work as expected. I'll update this issue once a fix has been released.

**Comment by ahuang11** [comment]
This should be fixed now. Please re-open if you still encounter this issue. Thank you!

**Comment by fedderw** [comment]
I think I'm having this issue - what is the deprecated method? That wasn't described here
