### ISSUE TITLE
Flows Using ECS Task infrastructure block crash when paused if using reschedule=True

### ISSUE THREAD

**Issue by jbnitorum** [PrefectHQ/prefect-aws#206]
When using the pause_flow_run function with argument reschedule=True on a flow with an ECS Task infrastructure block the expectation is that when paused the ECS task will be deprovisioned and the flow will remain in a Paused state.  When resumed a new ECS task will be provisioned and run the remaining flow tasks (similar to raise PAUSE in 1.0).

What I am seeing is that when the flow hits the Paused state the ECS task deprovisions and then the flow moves from a Paused state to a Crashed state.  The final State Message is "Flow run infrastructure exited with non-zero status code -1.".  The last log message on the ECS task is "21:55:46.456 | INFO | prefect.engine - Engine execution of flow run '09d19369-66ad-4f96-837a-09b713e3ff46' is paused:"

I am using a ECS Task infrastructure block on Fargate.  There doesn't seem to be any error other than that cloud is expecting the infrastructure to still be present and it is not.

Simple example flow code I am using:

```
from prefect import get_run_logger
from prefect import flow, task, pause_flow_run

@task(name="First Task", persist_result=True)
def first_task():
    logger=get_run_logger()
    logger.info('first task')
    return None
    
@task(name="Second Task", persist_result=True)
def second_task():
    logger=get_run_logger()
    logger.info('second task')
    return None

@flow(name="Test pause", result_storage='s3/prefect-results')
def test_pause_flow():
    first_result = first_task()
    pause_flow_run(reschedule=True, timeout=64800)
    second_result = second_task(wait_for=[first_result])
```

The ECS task definition was created using this terraform:  https://github.com/PrefectHQ/prefect-recipes/tree/main/devops/infrastructure-as-code/aws/tf-prefect2-ecs-agent

**Comment by desertaxle** [comment]
Thanks for opening an issue @jbnitorum! This appears to be a bug. I'll start investigation in our environment so that I replicate and formulate a fix for this issue.
