### ISSUE TITLE
Minio: Unable to locate credentials

### ISSUE THREAD

**Issue by KernelErr** [PrefectHQ/prefect-aws#210]
# Expectation / Proposal

Hi, when I use S3 Bucket (Minio) on prefect I got an error like:

```
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

After some investigation, I find that this line:

https://github.com/PrefectHQ/prefect-aws/blob/7a17997de8a61ad977549ed77e0ca6f669492d31/prefect_aws/s3.py#L305

If I change this line into:

```python
credentials: Optional[MinIOCredentials] = Field(
```

Things will be Ok.

Blocks:

![image](https://user-images.githubusercontent.com/45716019/218293969-94758a08-7853-43c7-a5aa-0bba67c142f7.png)

My python version: Python 3.10.10
prefect version: ==2.8.0
prefect-aws version: commit 7a17997de8a61ad977549ed77e0ca6f669492d31

# Traceback / Example

```python
from prefect import flow, task
from prefect_aws.s3 import S3Bucket
from prefect_aws import MinIOCredentials

@flow
def my_favorite_function():
    minio_credentials_block = MinIOCredentials.load("testblock")
    s3_bucket_block = S3Bucket(
        bucket_name="testblock",
        minio_credentials=minio_credentials_block
    )
    print(s3_bucket_block.list_objects(""))
    return "test"

print(my_favorite_function())
```

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

**Comment by KernelErr** [comment]
Update: I find another interesting bug, maybe related to this one.

If I install prefect by the following command:

```
pipenv install prefect prefect-aws
prefect orion start
```

And then I start a new orion instance. The `AWS Credentials` creation form will not have `AWS Client Parameters`. But if I install the prefect, start an orion, stop it, and install prefect-aws after that:

```
pipenv install prefect
prefect orion start
Ctrl-C
pipenv install prefect-aws
prefect orion start
```

The form will have these fields:

![image](https://user-images.githubusercontent.com/45716019/218300735-2d9022c3-1c50-4c06-88d7-e14bf94869b1.png)

I checked the SQLite database, there are duplicated `AwsCredentials` items in `block_schema` table, and they share the same `block_type_id`. So, when UI queries the filter API to get form fields, the first one returned to the JSON array will be used.

**Comment by tonal** [comment]
If downgrade **prefect-aws** to **0.2.4** all work ok.

**Comment by tonal** [comment]
From [**pydantic** doc](https://docs.pydantic.dev/usage/model_config/#smart-union):
> By default, as explained [here](https://docs.pydantic.dev/usage/types/#unions), pydantic tries to validate (and coerce if it can) in the order of the Union. So sometimes you may have unexpected coerced data.

If change order in **S3Bucket.credentials** type All work:
```python
    credentials: Optional[Union[MinIOCredentials, AwsCredentials]] = Field(
        default=None, description="A block containing your credentials to AWS or MinIO."
    )
```
Or add class setting **smart_union** = **True** in **class** Config for **S3Bucket**

**Comment by tonal** [comment]
see #251

**Comment by tonal** [comment]
Error in prefect-aws==0.3.2:
Register blocks:
```python
@sync_compatible
async def save_conf_blocks():
  endpoint_url = ENDPOINT_URL
  minio = MinIOCredentials.parse_obj(
    dict(name='epool-tk-upd-minio', minio_root_user=environ['MINIO_LOGIN'],
      minio_root_password=environ['MINIO_PASSW'],
      aws_client_parameters=dict(endpoint_url=endpoint_url), ))
  await minio.save('epool-tk-upd-minio', overwrite=True)

  s3_bucket_block = S3Bucket(
    name='epool-tk-upd', bucket_name='tk-upd-cache',
    credentials=minio, # minio_credentials=minio,
    endpoint_url=endpoint_url, )
  await s3_bucket_block.save('epool-tk-upd', overwrite=True)
```

Flow code:
```python
@task(cache_result_in_memory=False, persist_result=False, log_prints=True)
async def save_result(cache: WritableFileSystem, path, data):
  assert (
    isinstance(cache, LocalFileSystem) or
    isinstance(cache.credentials, MinIOCredentials)
  ), f'{cache}: {cache.credentials}'
  await cache.write_path(path, out_data)

@sync_compatible
async def s3_bucket_block() -> S3Bucket:
  _s3_bucket_block = await S3Bucket.load('epool-tk-upd')
  return _s3_bucket_block

@flow
def tk_upd_cache():
  cache=s3_bucket_block()
  save_result.submit(cache, 'tk_name', b'opa')
```

Error out:
```
Encountered exception during execution:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/engine.py", line 1623, in orchestrate_task_run
    result = await call.aresult()
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/prj/flows/tools.py", line 179, in save_result
    assert (
AssertionError: S3Bucket(bucket_name='tk-upd-cache', credentials=AwsCredentials(aws_access_key_id=None, aws_secret_access_key=None, aws_session_token=None, profile_name=None, region_name='ru-central1', aws_client_parameters=AwsClientParameters(api_version=None, use_ssl=True, verify=True, verify_cert_path=None, endpoint_url='https://s3.epool.ru', config=None)), bucket_folder=''): AwsCredentials(aws_access_key_id=None, aws_secret_access_key=None, aws_session_token=None, profile_name=None, region_name='ru-central1', aws_client_parameters=AwsClientParameters(api_version=None, use_ssl=True, verify=True, verify_cert_path=None, endpoint_url='https://s3.epool.ru', config=None))
01:43:44 PM
save_result-0
prefect.task_runs
```

**Comment by LR-Silva** [comment]
> see #251

I'm still getting this error on version prefect-aws==0.3.2. 
Its the same issue that @KernelErr reported, when i make the change he proposed it works fine but without it S3 loads the wrong config. 

I also noted that if I define the S3 block inside a Flow, using minio credentials block, it works fine but when getting the s3block  block directly it throws an error.
