### ISSUE TITLE
Specify volume to mount for ECSTask

### ISSUE THREAD

**Issue by jggatter** [PrefectHQ/prefect-aws#232]
# Proposal

[Slack thread](https://prefect-community.slack.com/archives/C048K0MGHNK/p1680623998032769)

When creating a deployment with the `ECSTask` Block, I would like to be able to specify an EFS/EBS volume for the ECS containers to use. This would make sharing large intermediate output files across flows easier, and would enable tasks which require the writing of large files to a filesystem.

From what I understand this functionality is not supported in [boto3.ECS.Client.start_task](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs/client/start_task.html) and would require the `"volumes"` and `"containerDefinitions.mountPoints"` fields of the task definition to be populated when task definition is registered.

# Example
```python
# Specify an already-created EFS or EBS volume to mount on the container
ECSTask(
    volume="my-efs-or-ebs-volume-name",
    ...
)
```
or
```python
# Automatically create and mount an EBS volume with a specified size and `deleteOnTermination: true`
ECSTask(
    size_gb=100,
    ...
)
```

- [?] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

**Comment by EmilRex** [comment]
On a broader note, it seems that `task_customizations` doesn't allow you to modify the actual task definition. It would be nice to have `task_definition_customizations` or something similar.

**Comment by madkinsz** [comment]
@EmilRex if you want to modify the task definition I feel like you ought to register one ahead of time — it's costly to for us to register a new one due to rate limits.

I believe this can be addressed by the worker project.

**Comment by jggatter** [comment]
Yes in fact I was just looking into what you mention @madkinsz, injecting my own task definition using the`task_definition` or `task_definition_arn` kwargs may be the workaround here.

I also discovered task definition's: `ephemeralStorage` is tweakable and a simpler alternative to what I've mentioned:
```
{
    ...
    "cpu": "16384",
    "memory": "65536",
    "ephemeralStorage": {
        "sizeInGiB": 100
    },
    ...
}
```

For now I've hardwired a task_definition_arn for a task definition that modifies this value, into my ECSTask block, but I may try something like this for my deployment building pipeline:

```python
default_task_definition = ECSTask()._prepare_task_definition({}, 'us-east-1')
default_task_definition['ephemeralStorage'] = {'sizeInGiB': 100}

ecs = ECSTask(
   ... # values that will override default_task_definition
   task_definition=default_task_definition,
)
```

Just want to clarify, what do you mean by "the worker project"?
