### ISSUE TITLE
Add ability to override S3 endpoint_url

### ISSUE THREAD

**Issue by davzucky** [PrefectHQ/prefect-aws#25]
They are a lot of alternatives to AWS S3 like [minio](https://min.io/) which are used in the enterprise.  To allow this module to work it would be nice to allow to pass to the S3 task a dictionary that would be used when we initialize the S3 client. For example from [boto3 doc](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-example-privatelink.html?highlight=endpoint_url)

This would allow as well to set up the verification when we are using a custom CA Bundle. https://github.com/boto/boto3/blob/develop/boto3/session.py.

If you are happy with that change I can create a PR for it.

**Comment by desertaxle** [comment]
Sounds like an excellent addition @davzucky and I'd be happy to review a PR for this contribution! I would recommend adding an attribute to the `AwsCredentials` class that can be used to pass additional configuration when creating a boto3 session. Let me know if you need any help!

**Comment by desertaxle** [comment]
I think strongly typed Dataclasses are preferable for the DX as long as the type they're representing is relatively stable.
