### ISSUE TITLE
Link to step-by-step guide under Contributing redirects to the Prefect-GCP documentation

### ISSUE THREAD

**Issue by Bada-S** [PrefectHQ/prefect-aws#252]
# Expectation / Proposal
The link should be corrected to the correct step by step guide or removed. There is already a link provided to Prefect-AWS documentation in the README

# Traceback / Example

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

**Comment by tinvaan** [comment]
Addressed in https://github.com/PrefectHQ/prefect-aws/pull/263/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by tinvaan** [comment]
This can be closed now that https://github.com/PrefectHQ/prefect-aws/pull/263 has landed.

/cc @desertaxle, @madkinsz

**Comment by desertaxle** [comment]
Thanks @tinvaan!
