### ISSUE TITLE
Reading AWS Secret 'SecretString'

### ISSUE THREAD

**Issue by nick-amplify** [PrefectHQ/prefect-aws#265]
# Expectation / Proposal
I'm using the awsSecretBlock and trying to read my secret
# Traceback / Example

The code is here: https://github.com/PrefectHQ/prefect-aws/blob/3a790e0f56d08f9268788dd8d6a95b27eb282db4/prefect_aws/secrets_manager.py#L409

My aws secret has it's response in "SecretString" key instead of "SecretBinary". 

Could this be added?

- [ x ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

**Comment by nchammas** [comment]
Dup of #262.
