### ISSUE TITLE
Error in version 0.4.8: TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by obendidi** [PrefectHQ/prefect-aws#372]
Latest release introduced client caching, and it hashes the credentials parameters for that (see https://github.com/PrefectHQ/prefect-aws/pull/369)

This introduced a bug, when I upgraded to `prefect-aws==0.4.8`:

```
  File "/home/user/lib/flows/my_flow.py", line 64, in my_flow
    s3: S3Client = aws_block.get_client("s3")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/lib/.venv/lib/python3.11/site-packages/prefect/events/instrument.py", line 73, in inner
    raise exc
  File "/home/user/lib/.venv/lib/python3.11/site-packages/prefect/events/instrument.py", line 70, in inner
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/lib.venv/lib/python3.11/site-packages/prefect_aws/credentials.py", line 170, in get_client
    return _get_client_cached(ctx=self, client_type=client_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/lib.venv/lib/python3.11/site-packages/prefect_aws/credentials.py", line 121, in __hash__
    hash(frozenset(self.aws_client_parameters.dict().items())),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

The usage of `hash(frozenset())` seems correct to me, so maybe it's a backward compatibility issue ? I upgraded from a pretty old version `~0.2`

# Expectation / Proposal

# Traceback / Example

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

**Comment by zzstoatzz** [comment]
hi @obendidi - thanks for the issue. looking into this now

**Comment by zzstoatzz** [comment]
reopening until the release is actually cut

**Comment by zzstoatzz** [comment]
hi @obendidi - `prefect-aws` v0.4.9 has now been released which should fix the hashing problem you raised here.

See #373 for details on the fix
